name: sns-message-verify
version: 0.1.0.0
github: "freckle/sns-message-verify"
license: BSD3
author: "Freckle"
maintainer: "engineering@freckle.com"
copyright: "2022 Freckle By Renaissance"
description: Please see the README on GitHub at <https://github.com/githubuser/sns-message-verify#readme>

extra-doc-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: library
  other-modules:
    - Amazon.SNS.Verify.Prelude
  dependencies:
    - aeson
    - bytestring
    - errors
    - http-conduit
    - memory
    - pem
    - safe
    - text
    - x509
    - x509-validation
    - http-types

tests:
  sns-message-verify-test:
    main: Main.hs
    source-dirs: tests
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - sns-message-verify
      - hspec
      - text
      - aeson-qq
      - aeson
      - x509-validation
