name: sns-webhook
version: 0.1.0.0
github: "freckle/sns-webhook"
license: BSD3
author: "Freckle"
maintainer: "engineering@freckle.com"
copyright: "2022 Freckle By Renaissance"
extra-source-files:
  - README.md
  - ChangeLog.md
description: Please see the README on GitHub at <https://github.com/githubuser/sns-webhook#readme>
dependencies:
  - base >= 4.7 && < 5
library:
  source-dirs: src
  other-modules:
    - Amazon.SNS.Webhook.Prelude
  dependencies:
    - aeson
    - bytestring
    - http-conduit
    - memory
    - pem
    - safe
    - text
    - x509
    - x509-validation
    - http-types
tests:
  sns-webhook-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - sns-webhook
      - hspec
      - text
      - aeson-qq
      - aeson
